from black_scholes import BlackScholes

def display_menu():
    print("Which Black-Scholes formula would you like to use?")
    print("1. Call Option Price")
    print("2. Put Option Price")
    print("3. Probability Call Option in the Money")
    print("4. Probability Put Option in the Money")
    print("5. Call Option Implied Volatility")
    print("6. Put Option Implied Volatility")

def process_choice(choice):
    if choice == 1:
        print("Recall: S = Stock Price, K = Strike Price, T = Time to Expiration (in years), r = Risk-Free Interest Rate, sigma = Volatility")
        inputs = input("Enter S, K, T, r, sigma separated by spaces: ").split()
        S = float(inputs[0])
        K = float(inputs[1])
        T = float(inputs[2])
        r = float(inputs[3])
        sigma = float(inputs[4])
        call_price = BlackScholes.call_price(S, K, T, r, sigma)
        print(f"Call Option Price: {call_price}")
        print(f"The price of a call option is {call_price} for stock price {S}, strike price {K}, time to expiration {T} years, risk-free rate {r}, and volatility {sigma}.")
    elif choice == 2:
        print("Recall: S = Stock Price, K = Strike Price, T = Time to Expiration (in years), r = Risk-Free Interest Rate, sigma = Volatility")
        inputs = input("Enter S, K, T, r, sigma separated by spaces: ").split()
        S = float(inputs[0])
        K = float(inputs[1])
        T = float(inputs[2])
        r = float(inputs[3])
        sigma = float(inputs[4])
        put_price = BlackScholes.put_price(S, K, T, r, sigma)
        print(f"Put Option Price: {put_price}")
        print(f"The price of a put option is {put_price} for stock price {S}, strike price {K}, time to expiration {T} years, risk-free rate {r}, and volatility {sigma}.")
    elif choice == 3:
        print("Recall: S = Stock Price, K = Strike Price, T = Time to Expiration (in years), r = Risk-Free Interest Rate, sigma = Volatility")
        inputs = input("Enter S, K, T, r, sigma separated by spaces: ").split()
        S = float(inputs[0])
        K = float(inputs[1])
        T = float(inputs[2])
        r = float(inputs[3])
        sigma = float(inputs[4])
        prob_call = BlackScholes.call_in_the_money(S, K, T, r, sigma)
        print(f"Probability Call Option in the Money: {prob_call}")
        print(f"The probability that a call option will be in the money at expiration is {prob_call} for stock price {S}, strike price {K}, time to expiration {T} years, risk-free rate {r}, and volatility {sigma}.")
    elif choice == 4:
        print("Recall: S = Stock Price, K = Strike Price, T = Time to Expiration (in years), r = Risk-Free Interest Rate, sigma = Volatility")
        inputs = input("Enter S, K, T, r, sigma separated by spaces: ").split()
        S = float(inputs[0])
        K = float(inputs[1])
        T = float(inputs[2])
        r = float(inputs[3])
        sigma = float(inputs[4])
        prob_put = BlackScholes.put_in_the_money(S, K, T, r, sigma)
        print(f"Probability Put Option in the Money: {prob_put}")
        print(f"The probability that a put option will be in the money at expiration is {prob_put} for stock price {S}, strike price {K}, time to expiration {T} years, risk-free rate {r}, and volatility {sigma}.")
    elif choice == 5:
        print("Recall: S = Stock Price, K = Strike Price, T = Time to Expiration (in years), r = Risk-Free Interest Rate, market_price = Market Price of Option")
        inputs = input("Enter market_price, S, K, T, r separated by spaces: ").split()
        market_price = float(inputs[0])
        S = float(inputs[1])
        K = float(inputs[2])
        T = float(inputs[3])
        r = float(inputs[4])
        implied_vol = BlackScholes.call_implied_volatility(market_price, S, K, T, r)
        print(f"Call Option Implied Volatility: {implied_vol}")
        print(f"The implied volatility for a call option with market price {market_price}, stock price {S}, strike price {K}, time to expiration {T} years, and risk-free rate {r} is {implied_vol}.")
    elif choice == 6:
        print("Recall: S = Stock Price, K = Strike Price, T = Time to Expiration (in years), r = Risk-Free Interest Rate, market_price = Market Price of Option")
        inputs = input("Enter market_price, S, K, T, r separated by spaces: ").split()
        market_price = float(inputs[0])
        S = float(inputs[1])
        K = float(inputs[2])
        T = float(inputs[3])
        r = float(inputs[4])
        implied_vol = BlackScholes.put_implied_volatility(market_price, S, K, T, r)
        print(f"Put Option Implied Volatility: {implied_vol}")
        print(f"The implied volatility for a put option with market price {market_price}, stock price {S}, strike price {K}, time to expiration {T} years, and risk-free rate {r} is {implied_vol}.")
    else:
        print("Invalid choice. Please select a valid formula number.")
